/*
 Navicat Premium Data Transfer

 Source Server         : root
 Source Server Type    : MySQL
 Source Server Version : 50528
 Source Host           : localhost:3306
 Source Schema         : graduation

 Target Server Type    : MySQL
 Target Server Version : 50528
 File Encoding         : 65001

 Date: 05/03/2019 22:01:45
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for admin
-- ----------------------------
DROP TABLE IF EXISTS `admin`;
CREATE TABLE `admin`  (
  `id` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '管理员登录ID',
  `password` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '管理员登录密码',
  `name` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '管理员姓名',
  `contact` varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '管理员联系方式',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Records of admin
-- ----------------------------
INSERT INTO `admin` VALUES ('admin', 'admin', '张迪', '17864195302');

-- ----------------------------
-- Table structure for exam_paper
-- ----------------------------
DROP TABLE IF EXISTS `exam_paper`;
CREATE TABLE `exam_paper`  (
  `title` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '试卷标题',
  `id` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '试卷唯一编号',
  `author` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '创作者姓名',
  `author_id` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '创作者id',
  `sub` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '试卷适应科目',
  `grade` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '试卷适应年级',
  `q_choice` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT '单选题（存储id数组）',
  `q_fill` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT '填空题',
  `q_big` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT '大题',
  `time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Records of exam_paper
-- ----------------------------
INSERT INTO `exam_paper` VALUES ('信工学院计算机专业计工本方向大二上数据库期末考试试题', '123', '张老师', '201511010123', '数据库', '大三', '120190209213338,120190209213724,120190209220427,120190209220602,120190209225339', '220190209113449,220190209221430,220190209222638', '320190211210558', '2019-02-13 23:11:01');
INSERT INTO `exam_paper` VALUES ('测试第一次手动生成试卷', '20151101012320190218232615', '张老师', '201511010123', 'C语言', '大三', '120190209213338,120190211205024,120190211205052,120190211205144,120190211205213,120190211214520,120190211215222', '220190211205510,220190211205601,220190211205820,220190211205923,220190211214702', '0', '2019-02-19 10:42:09');
INSERT INTO `exam_paper` VALUES ('测试自动生成试卷1', '20151101012320190228213956', '张老师', '201511010123', 'C语言', '大一', '120190209103423,120190209220427,120190209220533,120190209220602,120190209220746,120190209225202,120190209225339,120190210190745,120190210194356,120190210194506', '220190209221629,220190209221652,220190209222731,220190209223136,220190211205430', '320190209142201,320190211210558,320190211214752', '2019-02-28 21:39:56');
INSERT INTO `exam_paper` VALUES ('测试自动生成试卷第二次', '20151101012320190228215802', '张老师', '201511010123', 'C语言', '大二', '0', '220190209221550,220190209222656,220190209222747,220190209222936,220190209223149,220190210191814,220190210193755', '320190209142201,320190211210424,320190211211755', '2019-02-28 21:58:02');
INSERT INTO `exam_paper` VALUES ('信工学院计算机专业计工本方向大三上C语言期末考试试题', '23232', 'zzzz', '201511010111', '测试', '大一', '0', '220190210193816,220190210194127,220190210194112', '320190211210558', '2019-02-14 15:48:18');
INSERT INTO `exam_paper` VALUES ('信工学院计算机专业计工本方向大三上C语言期末考试试题', '321', '王老师', '201511010122', 'C语言', '大二', '120190209213801,120190209123407,120190209113419,120190209220503,120190209221049', '220190210193816,220190210194127,220190210194112', '320190211210424', '2019-02-14 14:22:32');

-- ----------------------------
-- Table structure for question
-- ----------------------------
DROP TABLE IF EXISTS `question`;
CREATE TABLE `question`  (
  `id` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '题目唯一编号(1开头单选题，2开头填空题，3开头大题)',
  `type` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '题目类型',
  `score` int(2) NOT NULL COMMENT '题目分值',
  `sub` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '题目适合科目',
  `content` text CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '题目内容',
  `answer` text CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '题目答案',
  `time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '插入时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Records of question
-- ----------------------------
INSERT INTO `question` VALUES ('120190209103423', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>C语言规定:在一个源程序中.main函数的位置。</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">必须在最开始</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">必须在系统调用的库函数的后面</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">可以任意</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">必须在最后</span></span></div>', 'C', '2019-02-09 21:01:56');
INSERT INTO `question` VALUES ('120190209113419', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>以下叙述正确的是。</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">在C程序中,main函数必须位于程序的最前面</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">C程序的每行中只能写一条语句</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">C语言本身没有输入输出语句</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">在对一个C程序进行编译的过程中,可发现注释中的拼写错误</span></span></div>', 'C', '2019-02-09 21:01:47');
INSERT INTO `question` VALUES ('120190209123407', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>一个C程序的执行是从（&nbsp;&nbsp;&nbsp;&nbsp;）。</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">本程序的main函数开始,到main函数结束</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">本程序文件的第一个函数开始,到本程序文件的最后一个函数结束</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">本程序的main函数开始,到本程序文件的最后一个函数结束</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">本程序文件的第一个函数开始,到本程序main函数结束</span></span></div>', 'A', '2019-02-09 21:01:34');
INSERT INTO `question` VALUES ('120190209213338', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>以下叙述不正确的是。</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">一个C源程序可由一个或多个函数组成</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">一个C源程序必须包含一个main函数</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">C程序的基本组成单位是函数</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">在C程序中,注释说明只能位于一条语句的后面</span></span></div>', 'D', '2019-02-14 14:17:28');
INSERT INTO `question` VALUES ('120190209213649', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>在C语言中(以16位PC机为例)，5种基本数据类型的存储空间长度的排列顺序为。</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">char < int < longint <＝ float < double</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">char ＝ int < longint <＝ float < double</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">char < int < longint ＝ float ＝ double</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">char ＝ int ＝ longint <＝ float < double</span></span></div>', 'A', '2019-02-09 22:39:53');
INSERT INTO `question` VALUES ('120190209213724', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>若x、i、j和k都是int型变量，则执行下面表达式后x的值为。</p><p>x＝(i＝4，j＝16，k＝32)</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">4</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">16</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">32</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">52</span></span></div>', 'C', '2019-02-09 21:37:24');
INSERT INTO `question` VALUES ('120190209213801', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>假设所有变量均为整型，则表达式(a＝2,b＝5,b＋＋,a＋b)的值是。</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">7</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">8</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">6</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">2</span></span></div>', 'B', '2019-02-09 21:38:01');
INSERT INTO `question` VALUES ('120190209214137', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>下列四组选项中，均不是C语言关键字的选项是。</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">define，IF，Type</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">getc，char，printf</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">include，scanf，case</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">while，go，pow</span></span></div>', 'A', '2019-02-09 21:41:37');
INSERT INTO `question` VALUES ('120190209215524', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>下面四个选项中,均是C语言关键字的选项是。</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">auto，enum，include</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">switch，type，continue</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">signed，define，scanf</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">if，struct，type</span></span></div>', 'B', '2019-02-09 21:55:24');
INSERT INTO `question` VALUES ('120190209215608', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>C语言中的标识符只能由字母、数字和下划线三种字符组成，且第一个</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">必须为字母</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">必须为下划线</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">必须为字母或下划线</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">可以是字母、数字和下划线中任一种字符</span></span></div>', 'C', '2019-02-09 21:56:08');
INSERT INTO `question` VALUES ('120190209215707', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>下面四个选项中,均是合法转义字符的选项是。</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">‘\\’’‘\\\\’‘\\n’</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">‘\\’‘\\017’‘\\”’</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">\\018’‘\\f’‘xab’</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">‘\\\\0’‘\\101’‘x1f’</span></span></div>', 'A', '2019-02-09 21:57:07');
INSERT INTO `question` VALUES ('120190209215748', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>下面正确的字符常量是。</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">“c”</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">‘\\’’</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">‘W’</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">‘’</span></span></div>', 'C', '2019-02-09 21:57:48');
INSERT INTO `question` VALUES ('120190209215816', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>下面不正确的字符串常量是。</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">‘abc’</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">“12\'12”</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">“0”</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">“”</span></span></div>', 'A', '2019-02-09 21:58:16');
INSERT INTO `question` VALUES ('120190209220155', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>若有代数式<img class=\"fr-fin\" data-fr-image-preview=\"false\" alt=\"Image title\" src=\"img/q_img/20190211213647uploadq1.png\" width=\"32\">，则不正确的C语言表达式是。</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">a/b/c*e*3</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">3*a*e/b/c</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">3*a*e/b*c</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">a*e/c/b*3</span></span></div>', 'C', '2019-02-11 21:36:50');
INSERT INTO `question` VALUES ('120190209220427', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>已知各变量的类型说明如下:</p><p>int k , a , b ;<br>unsigned long w ＝ 5 ;</p><p>double x ＝ 1.42 ;</p><p>则以下不符合C语言语法的表达式是。</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">x%(－3)</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">w＋＝－2</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">k＝(a＝2,b＝3,a＋b)</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">a＋＝a－＝(b＝4)*(a＝3)</span></span></div>', 'A', '2019-02-09 22:04:27');
INSERT INTO `question` VALUES ('120190209220503', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>以下不正确的叙述是。</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">在C程序中,逗号运算符的优先级最低</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">在C程序中，APH和aph是两个不同的变量</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">若a和b类型相同.在执行了赋值表达式a＝b后b中的值将放入a 中，而b中的值不变。</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">当从键盘输入数据时，对于整型变量只能输入整型数值,对于实型	变量只能输入实型数值。</span></span></div>', 'D', '2019-02-09 22:05:03');
INSERT INTO `question` VALUES ('120190209220533', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>以下正确的叙述是。</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">在C程序中，每行中只能写一条语句</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">若a是实型变量,C程序中允许赋值a＝10，因此实型变量中允许	存放整型数</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">在C程序中,无论是整数还是实数，都能被准确无误地表示</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">在C程序中,%是只能用于整数运算的运算符</span></span></div>', 'D', '2019-02-09 22:05:33');
INSERT INTO `question` VALUES ('120190209220602', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>以下符合C语言语法的赋值表达式是。</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">d＝9＋e＋f＝d＋9</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">d＝9＋e,f＝d＋9</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">d＝9＋e,e＋＋,d＋9</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">d＝9＋e＋＋＝d＋7</span></span></div>', 'B', '2019-02-09 22:06:02');
INSERT INTO `question` VALUES ('120190209220647', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>已知字母A的ASCII码为十进制数65，且c2为字符型，则执行语句c2＝\'A\'＋\'6\'－\'3\';后,c2中的值为。</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">D</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">68</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">不确定的值</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">C</span></span></div>', 'A', '2019-02-09 22:06:47');
INSERT INTO `question` VALUES ('120190209220723', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>在C语言中，int、char和short三种类型数据在内存中所占用的字节数。</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">由用户自己定义</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">均为2个字节</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">是任意的	</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">由所用机器的机器字长决定</span></span></div>', 'D', '2019-02-09 22:07:23');
INSERT INTO `question` VALUES ('120190209220746', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>若有说明语句:charc＝‘\\72’;则变量c。</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">包含1个字符</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">包含2个字符</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">包含3个字符</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">明不合法，c的值不确定</span></span></div>', 'A', '2019-02-09 22:07:46');
INSERT INTO `question` VALUES ('120190209220817', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>若有定义:inta＝7;floatx＝2.5,y＝4.7;则表达式x＋a%3*(int)(x＋y)%2/4的值是。</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">2.500000	</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">2.750000	</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">3.500000</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">0.000000</span></span></div>', 'A', '2019-02-09 22:08:17');
INSERT INTO `question` VALUES ('120190209220857', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>sizeof(float)是。</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">一个双精度型表达式</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">一个整型表达式</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">一种函数调用</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">一个不合法的表达式</span></span></div>', 'B', '2019-02-09 22:08:57');
INSERT INTO `question` VALUES ('120190209220939', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>若有代数式<img class=\"fr-fin\" data-fr-image-preview=\"false\" alt=\"Image title\" src=\"img/q_img/20190211213831uploadq2.png\" width=\"90\">,则正确的C语言表达式是。</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">sqrt	(fabs (pow(y,x)＋log(y)))</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">sqrt	(abs	(pow(y,x)＋log(y)))</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">sqrt	(fabs (pow(x,y)＋log(y)))</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">sqrt	(abs	(pow(x,y)＋log(y)))</span></span></div>', 'A', '2019-02-11 21:38:34');
INSERT INTO `question` VALUES ('120190209221049', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>设变量n为float类型,m为int类型,则以下能实现将n中的数值保留小数点后两位,第三位进行四舍五入运算的表达式是。</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">n＝(n*100＋0.5)/100.0</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">m＝n*100＋0.5，n＝m/100.0</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">n＝n*100＋0.5/100.0</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">n＝(n/100＋0.5)*100.0</span></span></div>', 'A', '2019-02-09 22:10:49');
INSERT INTO `question` VALUES ('120190209221209', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>设以下变量均为int类型,则值不等于7的表达式是。</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">(x＝y＝6,x＋y,x＋1)</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">(x＝y＝6,x＋y,y＋1)</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">(x＝6,x＋1,y＝6,x＋y)</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">(y＝6,y＋1,x＝y,x＋1)</span></span></div>', 'C', '2019-02-09 22:12:09');
INSERT INTO `question` VALUES ('120190209224203', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>putchar函数可以向终端输出一个</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">整型变量表达式值</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">实型变量值</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">字符串</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">字符或字符型变量值</span></span></div>', 'D', '2019-02-09 22:42:03');
INSERT INTO `question` VALUES ('120190209224624', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>已有定义inta＝－2;和输出语句：printf(\"%8lx\",a);以下正确的叙述是</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">整型变量的输出格式符只有%d一种</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">%x是格式符的一种,它可以适用于任何一种类型的数据</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">%x是格式符的一种,其变量的值按十六进制输出,但%8lx是错误的</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">%81x不是错误的格式符,其中数字8规定了输出字段的宽度</span></span></div>', 'D', '2019-02-09 22:46:24');
INSERT INTO `question` VALUES ('120190209225033', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>以下C程序正确的运行结果是。</p><p>main(){</p><p>inty＝2456;</p><p>printf(\"y＝%3o\\n\",y);</p><p>printf(\"y＝%8o\\n\",y);</p><p>printf(\"y＝%＃8o\\n\",y);</p><p>}</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">y＝2456 y＝2456 y＝＃＃＃＃＃＃＃＃2456</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">y＝4630 y＝4630 y＝＃＃＃＃＃＃＃＃4630</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">y＝2456 y＝2456 y＝02456</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">y＝4630 y＝4630 y＝04630</span></span></div>', 'D', '2019-02-09 22:50:33');
INSERT INTO `question` VALUES ('120190209225122', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>若x,y均定义为int型，z定义为double型，以下不合法的scanf函数调用语句是。</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">scanf(\"%d%lx,%le\",&x,&y,&z);</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">scanf(\"%2d*%d%lf\",&x,&y,&z);</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">scanf(\"%x%*d%o\",&x,&y);</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">scanf(\"%x%o%6.2f\",&x,&y,&z);</span></span></div>', 'D', '2019-02-09 22:51:22');
INSERT INTO `question` VALUES ('120190209225202', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>已有如下定义和输入语句,若要求a1,a2,c1,c2的值分别为10,20,A和B,当从第一列开始输入数据时,正确的数据输入方式是。</p><p>inta1,a2;charc1,c2;</p><p>scanf(\"%d%c%d%c\",&a1,&c1,&a2,&c2);</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">10A空格20B<CR></span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">10空格A空格20空格B<CR></span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">10A20B<CR></span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">10A20空格B<CR></span></span></div>', 'A', '2019-02-09 22:52:02');
INSERT INTO `question` VALUES ('120190209225242', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>已有如下定义和输入语句,若要求a1,a2,c1,c2的值分别为10,20,A和B,当从第一列开始输入数据时,正确的数据输入方式是。</p><p>inta1,a2;charc1,c2;</p><p>scanf(\"%d%d\",&a1,&a2);</p><p>scanf(\"%c%c\",&c1,&c2);</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">1020AB<CR></span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">10空格20<CR>AB<CR></span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">10空格空格20空格空格AB<CR></span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">10空格20AB<CR></span></span></div>', 'D', '2019-02-09 22:52:42');
INSERT INTO `question` VALUES ('120190209225339', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>已有程序段和输入数据的形式如下，程序中输入语句的正确形式应当为。</p><p>main(){</p><p>&nbsp;&nbsp;&nbsp;&nbsp;int a ; float f ;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;printf(\"\\nInputnumber:\");</p><p>&nbsp;&nbsp;&nbsp;&nbsp;输入语句</p><p>&nbsp;&nbsp;&nbsp;&nbsp;printf(\"\\nf＝%f,a＝%d\\n\",f,a);</p><p>}</p><p>Inputnumber:4.52&lt;CR&gt;</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">scanf(\"%d,%f\",&a,&f);</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">scanf(\"%f,%d\",&f,&a);</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">scanf(\"%d%f\",&a,&f);</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">scanf(\"%f%d\",&f,&a);</span></span></div>', 'D', '2019-02-09 22:53:39');
INSERT INTO `question` VALUES ('120190209225458', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>根据定义和数据的输入方式,输入语句的正确形式为。</p><p>已有定义: float f1，f2;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;数据的输入方式: 4.52&nbsp;&nbsp;&nbsp;&nbsp;3.5</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">scanf(\"%f,%f\",&f1,&f2);</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">scanf(\"%ff%f\",&f1,&f2);</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">scanf(\"%3.2f%2.1f\",&f1,&f2);</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">scanf(\"%3.2f%2.1f\",&f1,&f2);</span></span></div>', 'B', '2019-02-10 17:26:48');
INSERT INTO `question` VALUES ('120190209225833', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>阅读以下程序,当输入数据的形式为25,13,10正确的输出结果为。</p><p>main(){</p><p>&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;x , y , z ;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;scanf(\"%d%d%d\",&x,&y,&z);</p><p>&nbsp;&nbsp;&nbsp;&nbsp;printf(\"x＋y＋z＝%d\\n\",x＋y＋z);</p><p>&nbsp;&nbsp;&nbsp;&nbsp;}</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">x＋y＋z＝48</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">x＋y＋z＝35</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">x＋z＝35</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">不确定值</span></span></div>', 'D', '2019-02-09 23:00:19');
INSERT INTO `question` VALUES ('120190210173350', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>阅读以下程序,若运行结果为如下形式,输入输出语句的正确内容是。</p><p>main(){</p><p>&nbsp;&nbsp;&nbsp;&nbsp;int x ; float y ;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;printf( \"enterx,y:\"&nbsp;)</p><p>&nbsp;&nbsp;&nbsp;&nbsp;输入语句</p><p>&nbsp;&nbsp;&nbsp;&nbsp;输出语句</p><p>}</p><p>&nbsp;&nbsp;&nbsp;&nbsp;输入形式enterx,y:23.4</p><p>&nbsp;&nbsp;&nbsp;&nbsp;输出形式x＋y＝5.40</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">scanf(\"%d,%f”,&x,&y);\r\nprintf(\"\\nx＋y＝%4.2f\",x＋y);</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">scanf(\"%d%f\",&x,&y);\r\nprintf(\"\\nx＋y＝%4.2f\",x＋y);</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">scanf(\"%d%f\",&x,&y);\r\nprintf(\"\\nx＋y＝%6.1f\",x＋y);</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">scanf(\"%d%3.1f\",&x,&y);\r\nprintf(\"\\nx＋y＝%4.2f\",x＋y);</span></span></div>', 'B', '2019-02-10 17:33:50');
INSERT INTO `question` VALUES ('120190210173431', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>以下说法正确的是。</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">输入项可以为一实型常最,如scanf(\"%f\",3.5);</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">只有格式控制，没有输入项，也能进行正确输入，如scanf(\"a＝%d,b＝%d\");</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">当输人一个实型数据时，格式控制部分应规定小数点后的位数,如scanf(\"%4.2f\",&f);</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">当输入数据时,必须指明变量的地址,如scanf(\"%f\",&f);</span></span></div>', 'D', '2019-02-10 17:34:31');
INSERT INTO `question` VALUES ('120190210173551', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>根据下面的程序及数据的输入方式和输出形式，程序中输入语句的正确形式应该为。</p><p>main(){</p><p>&nbsp;&nbsp;&nbsp;&nbsp;char ch1,ch2,ch3;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;输入语句</p><p>&nbsp;&nbsp;&nbsp;&nbsp;printf(\"%c%c%c”,ch1,ch2,cb3);</p><p>&nbsp;&nbsp;&nbsp;&nbsp;}</p><p>&nbsp;&nbsp;&nbsp;&nbsp;输入形式:ABC</p><p>&nbsp;&nbsp;&nbsp;&nbsp;输出形式:AB</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">scanf(\"%c%c%c\",&ch1,&ch2,&ch3);</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">scanf(\"%c,%c,%c\",&ch1,&ch2,&ch3);</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">scanf(\"%c%c%c\",&ch1,&ch2,&ch3);</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">scanf(\"%c%c\",&ch1,&ch2,&ch3);</span></span></div>', 'A', '2019-02-10 17:35:51');
INSERT INTO `question` VALUES ('120190210173619', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>有输入语句：scanf(\"a＝%d,b＝%d,c＝%d\",&a,&b,&c);为使变量a的值为1,b为3,c为2,从键盘输入数据的正确形式应当是。</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">132<回车></span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">1,3,2<回车></span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">a＝1b＝3c＝2<回车></span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">a＝1,b＝3,c＝2<回车></span></span></div>', 'B', '2019-02-10 17:36:19');
INSERT INTO `question` VALUES ('120190210173647', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>以下能正确地定义整型变量a,b和c并为其赋初值5的语句是。</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">int a＝b＝c＝5;</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">int a,b,c＝5;</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">a＝5,b＝5,c＝5;</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">a＝b＝c＝5;</span></span></div>', 'A', '2019-02-10 17:36:47');
INSERT INTO `question` VALUES ('120190210173714', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>已知ch是字符型变量,下面不正确的赋值语句是。</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">ch＝\'a＋b\';	</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">ch＝\'\\0\';</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">ch＝\'7\'＋\'9\';</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">ch＝5＋9;</span></span></div>', 'A', '2019-02-10 17:37:14');
INSERT INTO `question` VALUES ('120190210173751', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>已知ch是字符型变量,下面正确的赋值语句是。</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">ch＝\'123\';</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">ch＝\'\\xff\';	</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">ch＝\'\\08\';</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">ch＝\"\\\";</span></span></div>', 'B', '2019-02-10 17:37:51');
INSERT INTO `question` VALUES ('120190210190745', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>若有以下定义，则正确的赋值语句是。</p><p>int a,b; float x;</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">a＝1,b＝2,</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">b＋＋;</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">a＝b＝5;</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">b＝int(x);</span></span></div>', 'B', '2019-02-10 19:07:45');
INSERT INTO `question` VALUES ('120190210190815', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>设x、y均为float型变量，则以下不合法的赋值语句是。</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">＋＋x;</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">y＝(x%2)/10;</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">x*＝y＋8;</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">x＝y＝0;</span></span></div>', 'B', '2019-02-10 19:08:15');
INSERT INTO `question` VALUES ('120190210190949', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>没x、y和z均为int型变量,则执行语句x＝(y＝(z＝10)＋5)－5;后,x、y和z的值是。</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">x＝10;\r\ny＝15;\r\nz＝10;</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">x＝10;\r\nz＝10;\r\ny=10;</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">x=10;\r\ny=10;\r\nz=15;</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">x=10;\r\ny=5;\r\nz=10</span></span></div>', 'A', '2019-02-10 19:09:49');
INSERT INTO `question` VALUES ('120190210191030', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>设有说明:doubley＝0.5，z＝1.5;intx＝10;则能够正确使用C语言库函数的赋值语句是。</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">z＝exp(y)＋fabs(x)</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">y＝log10(y)＋pow(y)</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">z＝sqrt(y－z)</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">x＝(int)(atan2((double)x,y)＋exp(y－0.2))</span></span></div>', 'D', '2019-02-10 19:10:30');
INSERT INTO `question` VALUES ('120190210194254', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>逻辑运算符两侧运算对象的数据据类型</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">只能是0或1</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">只能是0或非0正数</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">只能是整型或字符型数据</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">可以是任何类型的数据</span></span></div>', 'D', '2019-02-10 19:42:54');
INSERT INTO `question` VALUES ('120190210194327', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>以下关于运算符优先顺序的描述中正确的是。</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">关系运算符<算术运算符<赋值运算符<逻辑与运算符</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">逻辑与运算符<关系运算符<算术运算符<赋值运算符</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">赋值运算符<逻辑与运算符<关系运算符<算术运算符</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">算术运算符<关系运算符<赋值运算符<逻辑与运算符</span></span></div>', 'C', '2019-02-10 19:43:28');
INSERT INTO `question` VALUES ('120190210194356', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>下列运算符中优先级最高的是。</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\"><</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">＋</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">&&</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">!＝</span></span></div>', 'B', '2019-02-10 19:43:56');
INSERT INTO `question` VALUES ('120190210194421', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>能正确表示“当x的取值在[1,10]和[200,210]范围内为真，否则为假”的表达式是。</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">(x>＝1)&&(x<＝10)&&(x>＝200)&&(x<＝210)</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">(x>＝1)||(x<＝10)||(x>＝200)||(x<＝210)</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">(x>＝1)&&(x<＝10)||(x>＝200)&&(x<＝210)</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">(x>＝1)||(x<＝10)&&(x>＝200)||(x<＝210)</span></span></div>', 'C', '2019-02-10 19:44:21');
INSERT INTO `question` VALUES ('120190210194506', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>表示图中坐标轴上阴影部分的正确表达式是。</p><p><br><img class=\"fr-fin\" data-fr-image-preview=\"false\" alt=\"Image title\" src=\"img/q_img/20190211194232uploadq_106.png\" width=\"300\"></p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">(x<＝a)&&(x>＝b)&&(x<＝c)</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">(x<＝a)||(b<＝x<＝c)</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">(x<＝a)||(x>＝b)&&(x<＝c)</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">(x<＝a)&&(b<＝x<＝c)</span></span></div>', 'C', '2019-02-11 19:43:19');
INSERT INTO `question` VALUES ('120190211203957', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>判断char型变量ch是否为大写字母的正确表达式是。</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">\'A\'<＝ch<＝\'Z\'</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">(ch>＝\'A\')&(ch<＝\'Z\')</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">(ch>＝\'A\')&&(ch<＝\'Z\')</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">(\'A\'<＝ch)AND(\'Z\'>＝ch)</span></span></div>', 'C', '2019-02-11 20:39:57');
INSERT INTO `question` VALUES ('120190211204024', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>设x、y和z是int型变量,且x＝3,y＝4,z＝5，则下面表达式中值为0的是。</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">\'x\'&&\'y\'</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">x<＝y</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">x||y＋z&&y－z</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">!((x<y)&&!z||1)</span></span></div>', 'D', '2019-02-11 20:40:24');
INSERT INTO `question` VALUES ('120190211204048', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>已知x＝43,ch＝\'A\',y＝0;则表达式(x&gt;＝y&&ch&lt;\'B\'&&!y)的值是。</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">0</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">语法错</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">1</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">“假”</span></span></div>', 'C', '2019-02-11 20:40:48');
INSERT INTO `question` VALUES ('120190211204115', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>若希望当A的值为奇数时,表达式的值为“真”，A的值为偶数时,表达式的值为“假”。则以下不能满足要求的表达式是。</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">A%2＝＝1</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">!(A%2＝＝0)</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">!(A%2)</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">A%2</span></span></div>', 'C', '2019-02-11 20:41:15');
INSERT INTO `question` VALUES ('120190211204140', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>设有:inta＝1,b＝2,c＝3,d＝4,m＝2,n＝2;执行(m＝a&gt;b)&&(n＝c&gt;d)后n的值为。</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">1</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">2</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">3</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">4</span></span></div>', 'B', '2019-02-11 20:41:40');
INSERT INTO `question` VALUES ('120190211204204', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>判断char型变量c1是否为小写字母的正确表达式为。</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">\'a\'<＝c1<＝\'z\'</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">(c1>＝a)&&(cl<＝z)</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">(\'a\'>＝cl)||(\'z\'<＝c1)</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">(c1>＝\'a\')&&(c1<＝\'z\')</span></span></div>', 'D', '2019-02-11 20:42:04');
INSERT INTO `question` VALUES ('120190211204241', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>以下程序的运行结果是。</p><p>＃include\"stdio.h\"</p><p>main(){</p><p>&nbsp;&nbsp;&nbsp;&nbsp;int a,b,d＝241;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;a＝d/100%9;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;b＝(－1)&&(－1);</p><p>&nbsp;&nbsp;&nbsp;&nbsp;printf(\"%d,%d\",a,b);</p><p>}</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">6,1</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">2,1</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">6,0</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">2,0</span></span></div>', 'B', '2019-02-11 20:42:41');
INSERT INTO `question` VALUES ('120190211204357', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>以下不正确的if语句形式是。</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">if(x>y&&x!＝y);</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">if(x＝＝y)x＋＝y;</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">if(x!＝y)scanf(\"%d\",&x)elsescanf(\"%d\",&y);</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">if(x<y){x＋＋;y＋＋;}</span></span></div>', 'C', '2019-02-11 20:43:57');
INSERT INTO `question` VALUES ('120190211204428', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>已知intx＝l0,y＝20,z＝30;以下语句执行后x,y,z的值是。</p><p>if(x&gt;y)</p><p>z＝x;x＝y;y＝z;</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">x＝10,y＝20,z＝30</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">x＝20,y＝30,z＝30</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">x＝20,y＝30,z＝10</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">x＝20,y＝30,z＝20</span></span></div>', 'B', '2019-02-11 20:44:28');
INSERT INTO `question` VALUES ('120190211204456', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>以下if语句语法正确的是。</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">if(x>0)\r\nprintf(\"%f\",x)\r\nelse\r\nprintf(\"%f\",－x);</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">if(x>0)\r\n{x＝x＋y;printf(\"%f\",x);}\r\nelse\r\nprintf(\"%f\",－x);</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">if(x>0)\r\n{x＝x＋y;printf(\"%f\",x);};\r\nelse\r\nprintf(\"%f\",－x);</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">if(x>0)\r\n		{x＝x＋y;printf(\"%f\",x)}\r\nelse\r\nprintf(\"%f\",－x);</span></span></div>', 'A', '2019-02-11 20:45:20');
INSERT INTO `question` VALUES ('120190211204603', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>请阅读以下程序:</p><p>main(){</p><p>&nbsp;&nbsp;&nbsp;&nbsp;int a＝5,b＝0,c＝0;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;if(a＝b＋c)printf(\"***\\n\");</p><p>&nbsp;&nbsp;&nbsp;&nbsp;else			printf(\"$$$\\n\");</p><p>}</p><p>以上程序。</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">有语法错不能通过编译</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">可以通过编译但不能通过连接</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">输出***</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">输出$$$</span></span></div>', 'D', '2019-02-11 20:46:03');
INSERT INTO `question` VALUES ('120190211204625', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>以下程序的运行结果是。</p><p>main(){</p><p>&nbsp;&nbsp;&nbsp;&nbsp;int m＝5;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;if(m＋＋&gt;5)printf(\"%d\\n\",m);</p><p>&nbsp;&nbsp;&nbsp;&nbsp;else		printf(\"%d\\n\",m－－);</p><p>}</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">4</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">5</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">6</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">7</span></span></div>', 'C', '2019-02-11 20:46:25');
INSERT INTO `question` VALUES ('120190211204642', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>当a＝1,b－3,c＝5.d＝4时,执行完下面一段程序后x的值是。</p><p>if(a&lt;b)</p><p>if(c&lt;d&gt;x＝1</p><p>else</p><p>if(a&lt;c)</p><p>if(b&lt;d)x＝2;</p><p>elsex＝3;</p><p>elsex＝6;</p><p>elsex＝7;</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">1</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">2</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">3</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">6</span></span></div>', 'B', '2019-02-11 20:46:42');
INSERT INTO `question` VALUES ('120190211204920', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>以下程序的输出结果是。</p><p>main(){</p><p>&nbsp;&nbsp;&nbsp;&nbsp;int a＝100,x＝10,y＝20,ok1＝5,ok2＝0;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;if(x&lt;y)</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if(y!＝10)</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if(!ok1)</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;a＝1;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;else</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if(ok2)a＝10;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;a＝－1;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;printf(\"%d\\n\",a);</p><p>}</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">1</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">0</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">-1</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">值不确定</span></span></div>', 'C', '2019-02-11 20:49:20');
INSERT INTO `question` VALUES ('120190211204943', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>以下程序的输出结果是。</p><p>main()</p><p>{intx＝2,y＝－1,z＝2;</p><p>if(x&lt;y)</p><p>if(y&lt;0)z＝0;</p><p>elsez＋＝1;</p><p>printf(\"%d\\n\",z);</p><p>}</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">3</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">2</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">1</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">0</span></span></div>', 'B', '2019-02-11 20:49:43');
INSERT INTO `question` VALUES ('120190211205024', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>为了避免在嵌套的条件语句if－else中产生二义性,C语言规定:else子句总是与配对。</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">缩排位置相同的if</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">其之前最近的if</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">其之后最近的if</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">同一行上的if</span></span></div>', 'B', '2019-02-11 20:50:24');
INSERT INTO `question` VALUES ('120190211205052', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>以下不正确的语句为。</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">if(x>y);</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">if(x＝y)&&(x!＝0)x＋＝y;</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">if(x!＝y)scanf(\"%d\",&x);elsescanf(\"%d\",&y);</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">if(x<y){x＋＋;y＋＋;}</span></span></div>', 'B', '2019-02-11 20:50:52');
INSERT INTO `question` VALUES ('120190211205144', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>若有条件表达式(exp)?a＋＋:b－－,则以下表达式中能完全等价于表达式(exp)的是。</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">(exp＝＝0)</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">(exp!＝0)</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">(exp＝＝1)</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">(exp!＝1)</span></span></div>', 'B', '2019-02-11 20:51:44');
INSERT INTO `question` VALUES ('120190211205213', '单选题', 3, 'C语言', '<div class=\"exam-q\"><p>若运行时给变量x输入12,则以下程序的运行结果是。</p><p>main(){</p><p>&nbsp;&nbsp;&nbsp;&nbsp;int x,y;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;scanf(\"%d\",&x);</p><p>&nbsp;&nbsp;&nbsp;&nbsp;y＝x&gt;12?x＋10:x－12;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;printf(\"%d\\n\",y);</p><p>}</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">0</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">22</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">12</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">10</span></span></div>', 'A', '2019-02-11 20:52:13');
INSERT INTO `question` VALUES ('120190211214520', '单选题', 5, '数据库', '<div class=\"exam-q\"><p>123——单选题测试专用题——数据库</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">123——单选题测试专用答案A</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">123——单选题测试专用答案B</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">123——单选题测试专用答案C</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">123——单选题测试专用答案D</span></span></div>', 'A', '2019-02-11 21:45:53');
INSERT INTO `question` VALUES ('120190211215222', '单选题', 3, '高数', '<div class=\"exam-q\"><p>666——测试专用单选题——高数</p></div><div class=\"exam-o\"><span class=\"op\"><span class=\"op-item\">A、</span><span class=\"op-answer\">123——测试专用单选题答案A——高数</span></span><span class=\"op\"><span class=\"op-item\">B、</span><span class=\"op-answer\">123——测试专用单选题答案B——高数</span></span><span class=\"op\"><span class=\"op-item\">C、</span><span class=\"op-answer\">123——测试专用单选题答案C——高数</span></span><span class=\"op\"><span class=\"op-item\">D、</span><span class=\"op-answer\">123——测试专用单选题答案D——高数</span></span></div>', 'B', '2019-02-11 21:52:22');
INSERT INTO `question` VALUES ('220190209113443', '填空题', 4, 'C语言', '<div class=\"exam-q\">在C语言中,输入操作是由库函数__________完成的，输出操作是由库函数 __________完成的。</div>', '【1】scanf；【2】printf；', '2019-02-09 21:02:21');
INSERT INTO `question` VALUES ('220190209113449', '填空题', 4, 'C语言', '<div class=\"exam-q\"><p>在一个C源程序中,注释部分两侧的分界符分别为【1】和【2】。</p></div>', '【1】/*；【2】*/；', '2019-02-09 21:02:27');
INSERT INTO `question` VALUES ('220190209135855', '填空题', 6, 'C语言', '<div class=\"exam-q\"><p>若运行时输入:4.4&lt;回车&gt;,则以下程序的运行结果是。</p><p>＃include<stdio.h></stdio.h></p><p>voidmain(void)<br>{</p><p>floatCostPrice,SellingPrice;</p><p>printf(\"EnterCostPrice$:\");</p><p>scanf(\"%f\"，&CostPrice);</p><p>if(CostPrice&gt;＝5)</p><p>{</p><p>SellingPrice＝CostPrice＋CostPrice*0.25;</p><p>printf(\"SellingPrice(0.25)$%6.2f\"，SellingPrice);</p><p>}<br>else<br>{<br>SellingPrice＝CostPrice＋CostPrice*0.30;<br>printf(\"SellingPrice(0.30)$%6.2f\"，SellingPrice);}<br>}</p></div>', '【1】SellingPrice(0.30)$5.72；', '2019-02-09 21:02:41');
INSERT INTO `question` VALUES ('220190209213537', '填空题', 2, 'C语言', '<div class=\"exam-q\"><p>C源程序的基本单位是【】</p></div>', '【1】函数；', '2019-02-09 21:35:37');
INSERT INTO `question` VALUES ('220190209213601', '填空题', 2, 'C语言', '<div class=\"exam-q\"><p>一个C源程序中至少应包括一个【】</p></div>', '【1】主函数(或:main函数)；', '2019-02-09 21:36:01');
INSERT INTO `question` VALUES ('220190209221430', '填空题', 4, 'C语言', '<div class=\"exam-q\"><p>在C语言中(以16位PC机为例),一个char型数据在内存中所占的字节数为【1】;</p><p>一个int型数据在内存中所占的字节数为【2】。</p></div>', '【1】1；【2】2；', '2019-02-09 22:14:56');
INSERT INTO `question` VALUES ('220190209221447', '填空题', 4, 'C语言', '<div class=\"exam-q\"><p>在C语言中(以16位PC机为例),一个float型数据在内存中所占的字节数为【1】;</p><p>一个double型数据在内存中所占的字节数为【2】。</p></div>', '【1】4；【2】8；', '2019-02-09 22:14:47');
INSERT INTO `question` VALUES ('220190209221550', '填空题', 2, 'C语言', '<div class=\"exam-q\"><p>若有以下定义,则执行表达式y＋＝y－＝m*＝y后的y值是。</p><p>int m ＝ 5 , y ＝ 2 ;</p><p>我纠错试试看看前台反应如何！</p></div>', '【1】-16；', '2019-02-28 22:00:18');
INSERT INTO `question` VALUES ('220190209221629', '填空题', 2, 'C语言', '<div class=\"exam-q\"><p>设C语言中，一个int型数据在内存中占2个字节,则int型数据的取值范围为【】。</p></div>', '【1】－32768~＋32767；', '2019-02-09 22:16:29');
INSERT INTO `question` VALUES ('220190209221652', '填空题', 4, 'C语言', '<div class=\"exam-q\"><p>在C语言中的实型变量分为两种类型,它们是【1】和【2】。</p></div>', '【1】单精度型(或:float型)；【2】双精度型(或:double型)；', '2019-02-09 22:16:52');
INSERT INTO `question` VALUES ('220190209221720', '填空题', 6, 'C语言', '<div class=\"exam-q\"><p>C语言所提供的基本数据类型包括:单精度型、双精度型、【1】、【2】和【3】。</p></div>', '【1】整型；【2】字符型；【3】枚举型；', '2019-02-09 22:17:20');
INSERT INTO `question` VALUES ('220190209221735', '填空题', 2, 'C语言', '<div class=\"exam-q\"><p>若s是int型变量，且s＝6,则下面表达式的值为【】。</p><p>s%2＋(s＋1)%2</p></div>', '【1】1；', '2019-02-09 22:17:35');
INSERT INTO `question` VALUES ('220190209221750', '填空题', 2, 'C语言', '<div class=\"exam-q\"><p>若a是int型变量，则下面表达式的值为【】。</p><p>(a＝4*5,a*2)，a＋6</p></div>', '【1】26；', '2019-02-09 22:17:50');
INSERT INTO `question` VALUES ('220190209221809', '填空题', 4, 'C语言', '<div class=\"exam-q\"><p>若x和a均是int型变量，则执行表达式(1)后的x值为【1】，执行表达式(2)后的x值为【2】。</p><p>&nbsp;&nbsp;&nbsp;&nbsp;(1)x＝(a＝4,6*2)&nbsp; &nbsp;&nbsp;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;(2)x＝a＝4,6*2</p></div>', '【1】12；【2】4；', '2019-02-09 22:23:57');
INSERT INTO `question` VALUES ('220190209222638', '填空题', 4, 'C语言', '<div class=\"exam-q\"><p>若a、b和c均是int型变量,则执行下面表达式后,a值为【1】，b值为【2】，c值为【3】。</p><p>a＝(b＝4)＋(c＝2)</p></div>', '【1】6；【2】4；【3】2；', '2019-02-09 22:26:38');
INSERT INTO `question` VALUES ('220190209222656', '填空题', 4, 'C语言', '<div class=\"exam-q\"><p>若a是int型变量,且a的初值为6,则执行下面表达式后a的值为【】。<br>a＋＝a－＝a*a</p></div>', '【1】－60；', '2019-02-09 22:26:56');
INSERT INTO `question` VALUES ('220190209222704', '填空题', 4, 'C语言', '<div class=\"exam-q\"><p>若a是int型变量，则执行下面表达式后a的值为【】。</p><p>a＝25/3%3</p></div>', '【1】2；', '2019-02-09 22:27:04');
INSERT INTO `question` VALUES ('220190209222718', '填空题', 4, 'C语言', '<div class=\"exam-q\"><p>若x和n均是int型变量，且x和n的初值均为5,则执行下面表达式后x的值为【1】,n的值为【2】。</p><p>x＋＝n＋＋</p></div>', '【1】10；【2】6；', '2019-02-09 22:27:18');
INSERT INTO `question` VALUES ('220190209222731', '填空题', 2, 'C语言', '<div class=\"exam-q\"><p>若有定义:intb＝7;floata＝2.5,c＝4.7;则下面表达式的值为【】.</p><p>a＋(int)(b/3*(int)(a＋c)/2)%4</p></div>', '【1】5.500000；', '2019-02-09 22:28:02');
INSERT INTO `question` VALUES ('220190209222747', '填空题', 2, 'C语言', '<div class=\"exam-q\"><p>若有定义:inta＝2,b＝3;floatx＝3.5,y＝2.5;则下面表达式的值为【】.</p><p>(float)(a＋b)/2＋(int)x%(int)y</p></div>', '【1】3.500000；', '2019-02-09 22:27:56');
INSERT INTO `question` VALUES ('220190209222816', '填空题', 2, 'C语言', '<div class=\"exam-q\"><p>若有定义:charc＝‘\\010\';则变量c中包含的字符个数为【】。</p></div>', '【1】1；', '2019-02-09 22:28:16');
INSERT INTO `question` VALUES ('220190209222835', '填空题', 2, 'C语言', '<div class=\"exam-q\"><p>若有定义int x＝3，y＝2 ; float a＝2.5 , b＝3.5; 则下面表达式的值为【】。</p><p>(x＋y)%2＋(int)a/(int)b</p></div>', '【1】1；', '2019-02-09 22:29:58');
INSERT INTO `question` VALUES ('220190209222936', '填空题', 2, 'C语言', '<div class=\"exam-q\"><p>若x和n均是int型变量，且x的初值为12,n的初值为5,则执行下面表达式后x的值为【】.</p><p>x%＝(n%＝2)</p></div>', '【1】0；', '2019-02-09 22:29:36');
INSERT INTO `question` VALUES ('220190209223023', '填空题', 2, 'C语言', '<div class=\"exam-q\"><p>假设所有变量均为整型，则表达式(a＝2,b＝5,a＋＋,b＋＋,a＋b)的值为【】。</p></div>', '【1】9；', '2019-02-09 22:30:23');
INSERT INTO `question` VALUES ('220190209223136', '填空题', 6, 'C语言', '<div class=\"exam-q\"><p>C语言中的标识符只能由三种字符组求,它们是【1】,【2】和【3】。</p></div>', '【1】字母；【2】数字；【3】下划线；', '2019-02-09 22:31:36');
INSERT INTO `question` VALUES ('220190209223149', '填空题', 2, 'C语言', '<div class=\"exam-q\"><p>已知字母a的ASCII码为十进制数97,且设ch为字符型交量,则表达式ch＝\'a\'＋\'8\'－\'3\'的值为【】。</p></div>', '【1】f；', '2019-02-09 22:31:49');
INSERT INTO `question` VALUES ('220190209223205', '填空题', 2, 'C语言', '<div class=\"exam-q\"><p>把以下多项式写成只含七次乘法运算，其余皆为加、减运算的表达式为【】。</p><p>5X^7＋3X^6－4X^5＋2X^4＋X^3－6X^2＋X＋10</p></div>', '【1】X*(X*(X*(X*(X*(X*(5*X＋3)－4)＋2)＋1)－6)＋1)＋10；', '2019-02-09 22:32:05');
INSERT INTO `question` VALUES ('220190209223217', '填空题', 2, 'C语言', '<div class=\"exam-q\"><p>若x和y都是double型变量，且x的初值为3.0,y的初值为2.0,则表达式pow(y，fabs(x))的值为【】</p></div>', '【1】8.00000；', '2019-02-09 22:32:17');
INSERT INTO `question` VALUES ('220190209223252', '填空题', 2, 'C语言', '<div class=\"exam-q\"><p>若有定义:inte＝1,f＝4,g＝2;floatm＝10.5,n＝4.0,k;则执行赋值表达式k＝(e＋f)/gsqrt((double)n)*1.2/g＋m后k的值是【】.</p></div>', '【1】13.70000；', '2019-02-09 22:32:52');
INSERT INTO `question` VALUES ('220190209223316', '填空题', 2, 'C语言', '<div class=\"exam-q\"><p>表达式8/4*(int)2.5/(int)(1.25*(3.7＋2.3))值的数据类型为【】</p></div>', '【1】整型(或:int型)；', '2019-02-09 22:33:16');
INSERT INTO `question` VALUES ('220190209223330', '填空题', 2, 'C语言', '<div class=\"exam-q\"><p>表达式pow(2.8，sqrt(double(x)))值的数据类型为【】。</p></div>', '【1】双精度型(或:double型)；', '2019-02-09 22:33:30');
INSERT INTO `question` VALUES ('220190209223343', '填空题', 2, 'C语言', '<div class=\"exam-q\"><p>假设m是一个三位数,从左到右用a、b、c表示各位的数字,则从左到右各个数字是bac的三位数的表达式是【】。</p></div>', '【1】m/10%10*100＋m/100*10＋m%10；', '2019-02-09 22:33:43');
INSERT INTO `question` VALUES ('220190210191331', '填空题', 4, 'C语言', '<div class=\"exam-q\"><p>以下程序的输出结果为。</p><p>main(){</p><p>&nbsp;&nbsp;&nbsp;&nbsp;short i ;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;i＝－4;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;printf( \"\\ni:dec＝%d,oct＝%o,hex＝%x,unsigned＝%u\\n\",i,i,i,i );</p><p>&nbsp;&nbsp;&nbsp;&nbsp;}</p></div>', '【1】i:dec＝－4,oct＝177774,hex＝fffc,unsigned＝65532；', '2019-02-10 19:13:31');
INSERT INTO `question` VALUES ('220190210191413', '填空题', 4, 'C语言', '<div class=\"exam-q\"><p>以下程序的输出结果为。</p><p>main(){</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;printf(\"*%f,%4.3f*\\n\"3.14,3.1415);</p><p>&nbsp;&nbsp;&nbsp;&nbsp;}</p></div>', '【1】*3.140000,3.142*；', '2019-02-10 19:14:24');
INSERT INTO `question` VALUES ('220190210191506', '填空题', 4, 'C语言', '<div class=\"exam-q\"><p>以下程序的输出结果为。</p><p>main(){</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; char c＝ \'x\' ;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;printf(\"c:dec＝%d,oct＝%o,hex＝%x，ASCII＝%c\\n\"c,c,c,c);</p><p>&nbsp;&nbsp;&nbsp;&nbsp;}</p></div>', '【1】c:dec＝＝120，oct＝170，hex＝78,ASCII＝x；', '2019-02-10 19:15:06');
INSERT INTO `question` VALUES ('220190210191535', '填空题', 4, 'C语言', '<div class=\"exam-q\"><p>已有定义intd＝－2;执行以下语句后的输出结果是。</p><p>printf(\"*d(1)＝%d＋d(2)＝%3d*d(3)＝%－3d*\\n\",d,d,d);</p><p>&nbsp;&nbsp;&nbsp;&nbsp;printf(\"*d(4)＝%o*d(5)＝%7o*d(6)＝%－7o*\\n\",d,d,d);</p></div>', '【1】*d(1)＝－2*d(2)＝－2*d(3)＝－2*\r\n；【2】*d(4)＝177776*d(5)＝177776*d(6)＝177776*；', '2019-02-10 19:15:56');
INSERT INTO `question` VALUES ('220190210191645', '填空题', 4, 'C语言', '<div class=\"exam-q\"><p>已有定义intd＝－2;执行以下语句后的输出结果是。</p><p>printf(\"*d(1)＝%d*d(2)＝%3d*d(3)＝%－3d*\\n\",d,d,d);</p><p>&nbsp;&nbsp;&nbsp;&nbsp;printf(\"*d(4)＝%x*d(5)＝%6x*d(6)＝%－6x*\\n\"d,d,d);</p></div>', '【1】*d(1)＝－2*d(2)＝－2*d(3)＝－2*；【2】*d(4)＝fffe*d(5)＝fffe*d(6)＝fffe*；', '2019-02-10 19:16:45');
INSERT INTO `question` VALUES ('220190210191702', '填空题', 4, 'C语言', '<div class=\"exam-q\"><p>已有定义floatd1＝3.5,d2＝－3.5;执行以下语句后的输出结果是。</p><p>printf(\"*d(1)＝%e*d(2)＝%.4e*d(3)＝%10.4e*\\n\",d1,d1,d1);</p><p>printf(\"*d(4)＝%e*d(5)＝%.6e*d(6)＝%－12.5e*\\n\",d2,d2,d2);</p></div>', '【1】*d(1)＝3.50000e＋00*d(2)＝3.500e＋00*d(3)＝3.500e＋00*；【2】*d(4)＝－3.50000e＋00*d(5)＝－3.50000e＋00xd(6)＝－3.5000e＋00；', '2019-02-10 19:37:02');
INSERT INTO `question` VALUES ('220190210191814', '填空题', 4, 'C语言', '<div class=\"exam-q\"><p>以下程序的输出结果是。</p><p>main(){</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;int x＝1 , y＝2;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;printf( \"x＝%dy＝%d*sum*＝%d\\n\"x,y,x＋y );</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;printf( \"10Squaredis：%d\\n\",10*10 );</p><p>&nbsp;&nbsp;&nbsp;&nbsp;}</p></div>', '【1】x＝1y＝2*sum*＝3<换行>\r\n10Squaredis:100；', '2019-02-10 19:19:21');
INSERT INTO `question` VALUES ('220190210192823', '填空题', 4, 'C语言', '<div class=\"exam-q\"><p>以下程序的输出结果是。</p><p>＃include&lt;stdio.h&gt;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;main(){</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;int a＝325;double x＝3.1415926;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;printf(\"a＝%＋06d		x＝%＋e\\n\",a,x);</p><p>}</p></div>', '【1】a＝＋00325_ _ _x＝＋3.14159e＋00(此处_代表空格)；', '2019-02-10 19:30:30');
INSERT INTO `question` VALUES ('220190210192910', '填空题', 4, 'C语言', '<div class=\"exam-q\"><p>以下程序的输出结果是。</p><p>＃include&lt;stdio.h&gt;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;main(){</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;int a＝252;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;printf(\"a＝%oa＝%＃o\\n\",a,a);</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;printf(\"a＝%xa＝%＃x\\n\",a,a);</p><p>}</p></div>', '【1】a＝374_ _a＝0374<换行>\r\na＝fc_ _a＝0xfc			(此处_代表空格)；', '2019-02-10 19:29:10');
INSERT INTO `question` VALUES ('220190210193726', '填空题', 4, 'C语言', '<div class=\"exam-q\"><p>假设变量a和b均为整型,以下语句可以不借助任何变量把e、b中的值进行交换。请填空。</p><p>a＋＝【1】;b＝a－【2】;a－＝【3】;</p></div>', '【1】b；【2】b；【3】b；', '2019-02-10 19:37:26');
INSERT INTO `question` VALUES ('220190210193755', '填空题', 4, 'C语言', '<div class=\"exam-q\"><p>假设变量a、b和c均为整型，以下语句借助中间变量t把a、b和c中的值进行交换,即:把b中的值给a,把c中的值给b,把a中的值给c。例如:交换前,a＝10、b＝20、c＝30;交换后,a＝20,b＝30,c＝10。请填空。</p><p>【1】;a＝b ; b＝c;【2】;</p></div>', '【1】t＝a；【2】c＝t；', '2019-02-10 19:37:55');
INSERT INTO `question` VALUES ('220190210193816', '填空题', 4, 'C语言', '<div class=\"exam-q\"><p>设x、y和z都是int型变量，m为long型变量，则在16位微型机上执行下面赋值语句后，y值为【1】，z值为【2】,m值为【3】。</p><p>y＝(x＝32767,x－1);</p><p>z＝m＝0xFFFF;</p></div>', '【1】32766；【2】－1；【3】65535；', '2019-02-10 19:38:16');
INSERT INTO `question` VALUES ('220190210193829', '填空题', 4, 'C语言', '<div class=\"exam-q\"><p>若x为int型变量,则执行以下语句后x的值是【】。</p><p>x＝7;</p><p>x＋＝x－＝x＋x;</p></div>', '【1】－14；', '2019-02-10 19:38:29');
INSERT INTO `question` VALUES ('220190210193856', '填空题', 4, 'C语言', '<div class=\"exam-q\"><p>若a和b均为int型变量，则以下语句的功能是【】。</p><p>a＋＝b ; b＝a－b ; a－＝b;</p></div>', '【1】不借助任何中间变量把a.b中的值进行交换。；', '2019-02-10 19:38:56');
INSERT INTO `question` VALUES ('220190210193926', '填空题', 4, 'C语言', '<div class=\"exam-q\"><p>在scanf函数调用语句中,可以在格式字符和%号之间加一星号,它的作用是【1】;当输入以下数据:10[][]20[][]30[][]40&lt;回车&gt;(此处[]代表空格)，下面语句的执行结果是【2】。</p><p>int a1,a2,a3;</p><p>scanf(\"%d%	*	d%d%d\",&a1,&a2,&a3);</p></div>', '【1】跳过对应的输入数据；【2】输入以下数据时:10__20__30__40<回车>将把10赋给a1,跳过20,把30赋给a2,把40赋给a3；', '2019-02-10 19:39:26');
INSERT INTO `question` VALUES ('220190210193954', '填空题', 4, 'C语言', '<div class=\"exam-q\"><p>有一输入函数scanf(\"%d\",k);其不能使float类型变量k得到正确数值的原因是【1】和【2】。</p></div>', '【1】未指明变量k的地址；【2】格式控制符与变量类型不匹配，scanf语句的正确形式应该是:scanf(\"%f\",&k);；', '2019-02-10 19:39:54');
INSERT INTO `question` VALUES ('220190210194011', '填空题', 4, 'C语言', '<div class=\"exam-q\"><p>已有定义inta;floatb,x;charc1,c2;为使a＝3,b＝6.5,x＝12.6，c1＝\'a\',c2＝\'A\',正确的scanf函数调用语句是【1】,输入数据的方式为【2】。</p></div>', '【1】scanf(\"%d%f%f%c%c\",&a,&b,&c1,&c2);；【2】3_6.5_12.6aA<回车>；', '2019-02-10 19:40:11');
INSERT INTO `question` VALUES ('220190210194027', '填空题', 4, 'C语言', '<div class=\"exam-q\"><p>若有以下定义和语句，为使变量C1得到字符‘A’,变量C2得到字符‘B’,正确的格式输入形式是。</p><p>char c1,c2;</p><p>scanf(\"%4c%4c\",&c1,&c2);</p></div>', '【1】A___B___<回车>；', '2019-02-10 19:40:27');
INSERT INTO `question` VALUES ('220190210194112', '填空题', 4, 'C语言', '<div class=\"exam-q\"><p>执行以下程序时,若从第一列开始输入数据,为使变量a＝3,b＝7,x＝8.5，y＝71.82,c1＝‘A’,c2＝‘a\',正确的数据输入形式是。</p><p>main(){</p><p>&nbsp;&nbsp;&nbsp;&nbsp;int a,b;float x , y;char c1,c2;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;scanf(\"a＝%db＝%d\",&a,&b);</p><p>&nbsp;&nbsp;&nbsp;&nbsp;scanf(\"x＝%fy＝%f\",&x,&y);</p><p>&nbsp;&nbsp;&nbsp;&nbsp;scanf(\"c1＝%cc2＝%c\",&c1,&c2);</p><p>&nbsp;&nbsp;&nbsp;&nbsp;printf(\"a＝%d,b＝%d,x＝%f,y＝%f,cl＝%c,c2＝%c\",a,b,x,y,cl,c2);</p><p>}</p></div>', '【1】a＝3_b＝7x＝8.5_y＝71.82c1＝A_c2＝a<回车>；', '2019-02-10 19:41:12');
INSERT INTO `question` VALUES ('220190210194127', '填空题', 4, 'C语言', '<div class=\"exam-q\"><p>已有定义inti,j;floatx;为将－10赋给i,12赋给j,410.34赋给x;则对应以下scanf函数调用语句的数据输入形式是。</p><p>scanf(\"%o%x%e\",&i,&j,&x);</p></div>', '【1】－12_c_4.1034e＋02<回车>；', '2019-02-10 19:41:27');
INSERT INTO `question` VALUES ('220190211205241', '填空题', 2, 'C语言', '<div class=\"exam-q\"><p>当a＝3,b＝2,c＝1时,表达式f＝a&gt;b&gt;c的值是【】。</p></div>', '【1】0；', '2019-02-11 20:52:41');
INSERT INTO `question` VALUES ('220190211205410', '填空题', 2, 'C语言', '<div class=\"exam-q\"><p>设y为int型变量,请写出描述\"y是奇数\"的表达式【】。</p></div>', '【1】(y%2)＝＝1；', '2019-02-11 20:54:10');
INSERT INTO `question` VALUES ('220190211205430', '填空题', 2, 'C语言', '<div class=\"exam-q\"><p>有int	x,y,z;且x＝3,y＝－4,z＝5,则表达式x＋＋－y＋(＋＋z)的值为【】。</p></div>', '【1】13；', '2019-02-11 20:54:30');
INSERT INTO `question` VALUES ('220190211205510', '填空题', 4, 'C语言', '<div class=\"exam-q\"><p>若运行时输入:16&lt;回车&gt;，则以下程序的运行结果是。</p><p>＃include&lt;stdio.h&gt;</p><p>void main(void){</p><p>&nbsp;&nbsp;&nbsp;&nbsp;int year;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;printf(\"Inputyouyear:\");</p><p>&nbsp;&nbsp;&nbsp;&nbsp;scanf(\"%d\"，&year);</p><p>&nbsp;&nbsp;&nbsp;&nbsp;if(year&gt;＝18)</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;printf(\"you$4.5yuan/xiaoshi\");</p><p>&nbsp;&nbsp;&nbsp;&nbsp;else</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;printf(\"your$3.0yuan/xiaoshi\");</p><p>}</p></div>', '【1】your$3.0yuan/xiaoshi；', '2019-02-11 20:55:10');
INSERT INTO `question` VALUES ('220190211205601', '填空题', 2, 'C语言', '<div class=\"exam-q\"><p>若运行时输入:5999&lt;回车&gt;,则以下程序的运行结果(保留小数点后一位)是。</p><p>main(){	</p><p>&nbsp;&nbsp;&nbsp;&nbsp;int x;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;float y;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;scanf(\"%d\",&x);</p><p>&nbsp;&nbsp;&nbsp;&nbsp;if(x&gt;＝0&&x&lt;＝2999)y＝18＋0.12*x;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;if(x&gt;＝3000&&x&lt;＝5999)y＝36＋0.6*x;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;if(x&gt;＝6000&&x&lt;＝10000)y＝54＋0.3*x;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;printf(\"%6.1f\",y);</p><p>}</p></div>', '【1】3635.4；', '2019-02-11 20:56:01');
INSERT INTO `question` VALUES ('220190211205656', '填空题', 2, 'C语言', '<div class=\"exam-q\"><p>以下程序实现输出x,y,z三个数中的最大者。请在【】内填入正确内容。</p><p>main(){	</p><p>&nbsp;&nbsp;&nbsp;&nbsp;int x＝4,y＝6,z＝7;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;int【1】;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;if(【2】)</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;u＝x;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;else</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;u＝y;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;if(【3】)</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;v＝u;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;else</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;v＝z;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;printf(\"v＝%d\",v);</p><p>}</p></div>', '【1】u,v；【2】x>y；【3】u>z；', '2019-02-11 20:56:56');
INSERT INTO `question` VALUES ('220190211205820', '填空题', 4, 'C语言', '<div class=\"exam-q\"><p>有四个数a,b,c,d,要求按从大到小的顺序输出。请在【】内填入正确内容。</p><p>main(){</p><p>&nbsp;&nbsp;&nbsp;&nbsp;inta,b,c,d,t;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;scanf(\"%d%d%d%d\",&a,&b,&c,&d);</p><p>&nbsp;&nbsp;&nbsp;&nbsp;if(a</p><p>&nbsp;&nbsp;&nbsp;&nbsp;if(【1】){t＝c;c＝d;d＝t;}</p><p>&nbsp;&nbsp;&nbsp;&nbsp;if(a</p><p>&nbsp;&nbsp;&nbsp;&nbsp;if(【2】){t＝b;b＝c;c＝t;}</p><p>&nbsp;&nbsp;&nbsp;&nbsp;if(b</p><p>&nbsp;&nbsp;&nbsp;&nbsp;if(c</p><p>&nbsp;&nbsp;&nbsp;&nbsp;printf(\"%d%d%d%d\\n\",a,b,c,d);</p><p>}</p></div>', '【1】c<d；【2】b<c；', '2019-02-11 20:58:53');
INSERT INTO `question` VALUES ('220190211205923', '填空题', 2, 'C语言', '<div class=\"exam-q\"><p>设有变量定义:	int	a＝10,c＝9;则表达式(－－a!＝c＋＋)?－－a:＋＋c的值是【】。</p></div>', '【1】11；', '2019-02-11 20:59:23');
INSERT INTO `question` VALUES ('220190211214702', '填空题', 5, '数据库', '<div class=\"exam-q\"><p>123——填空题测试专用——数据库，两个空【1】，【2】</p></div>', '【1】123——填空专用答案——（1）；【2】123——填空专用填空——（2）；', '2019-02-11 21:55:10');
INSERT INTO `question` VALUES ('220190211215342', '填空题', 4, '高数', '<div class=\"exam-q\"><p>123——测试专用填空题——高数【1】</p><p><img class=\"fr-fil\" data-fr-image-preview=\"false\" alt=\"Image title\" src=\"img/q_img/20190211215309uploadcat1.png\" width=\"300\"></p><p><br></p></div>', '【1】123——测试专用填空题答案；', '2019-02-16 15:56:04');
INSERT INTO `question` VALUES ('320190209142201', '大题', 8, 'C语言', '<div class=\"exam-q\"><p>请编程序:根据以下函数关系,对输入的每个x值,计算出相应的y值。</p><p><img src=\"img/q_img/20190211212936upload%E5%9B%BE%E7%89%872.png\" class=\"fr-fin\" width=\"248\"><br></p></div>', '<p>main( )&nbsp;{&nbsp;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;int x;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;float y;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;scanf( \"%d\" , &x );</p><p>&nbsp;&nbsp;&nbsp;&nbsp;if(x&nbsp; &lt; 0)&nbsp;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;y ＝ 0;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;else if( x &gt; 0&&x &lt;＝ 10 )</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;y ＝ x;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;else if( x &gt; 10&& x &lt;＝ 20 )</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;y ＝ 10;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;else if( x &gt; 20&& x &lt; 40 )</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;y ＝ －0.5*x＋20;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;else</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;y ＝ －1 ;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;if( y !＝ －1 )</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;printf( %f\" , y ) ;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;else</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;printf( \"error\\n\" ) ;</p><p>}&nbsp;</p>', '2019-02-11 21:30:21');
INSERT INTO `question` VALUES ('320190210192623', '大题', 4, 'C语言', '<div class=\"exam-q\"><p>以下printf语句中*号的作用是【1】,输出结果是【2】</p><p>＃include<stdio.h></stdio.h></p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;main(){</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;int i;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for(i＝1;i&lt;＝5;i＋＋)</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;printf(\"＃＃%*d\\n\",i,i);</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}</p><p><br></p></div>', '<p>【1】可以使同一输出语句中的输出宽度得以改变。</p><p>【2】</p><p>##1</p><p>##_2</p><p>##_&nbsp;_3</p><p>##_&nbsp;_&nbsp;_4</p><p>##_&nbsp;_&nbsp;_&nbsp;_5(此处_代表空格)</p>', '2019-02-11 21:30:03');
INSERT INTO `question` VALUES ('320190210193055', '大题', 4, 'C语言', '<div class=\"exam-q\"><p>以下程序段的输出结果是。</p><p>int x＝7281;</p><p>printf(\"(1)x＝%3d,x＝%6d,x＝%6o，x＝%6x,x＝%6u\\n\",x,x,x,x,x);</p><p>printf(\"(2)x＝%－3d,x＝%－6d,x＝$%－06d,x＝$%06d，x＝%%06d\\n\",x,x,x,x,x);</p><p>printf(\"(3)x＝%＋3d,x＝%＋6d,x＝%＋08d\\n\",x,x,x);</p><p>printf(\"(4)x＝%o,x＝%＃o\\n\",x,x);</p><p>printf(\"(5)x＝%x，x＝%＃x\\n\",x,x);</p></div>', '<p>(1)x＝7281,x＝7281,x＝16161,x＝1c71，x＝7281</p><p>(2)x＝7281,x＝7281，x＝$7281，x＝$007281,x＝%06d</p><p>(3)x＝＋7281，x＝＋7281,x＝＋0007281</p><p>(4)x＝16161，x＝016161</p><p>(5)x＝1c71,x＝0x1c71</p>', '2019-02-10 19:30:55');
INSERT INTO `question` VALUES ('320190211210338', '大题', 15, 'C语言', '<div class=\"exam-q\"><p>编制程序要求输入整数a和b,若a^2＋b^2大于100,则输出a^2＋b^2百位以上的数字，否则输出两数之和。</p></div>', '<p>&nbsp;&nbsp;&nbsp;&nbsp;main(){&nbsp;&nbsp;&nbsp;&nbsp;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;int a , b , x , y ;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;scanf( \"%d%d , &a,&b ) ;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;x＝a*a＋b*b ;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if( x&gt;100 ){</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;y＝x/100 ;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;printf(\"%d,y);</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}</p><p>&nbsp;&nbsp;&nbsp;&nbsp;else</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;printf( \"%d,a＋b );</p><p>}</p>', '2019-02-11 21:03:38');
INSERT INTO `question` VALUES ('320190211210424', '大题', 15, 'C语言', '<div class=\"exam-q\"><p>试编程判断输入的正整数是否既是5又是7的整倍数。若是,则输出yes;否则输出no。</p></div>', '<p>&nbsp;&nbsp;&nbsp;&nbsp;main(){</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;int x;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;scanf(\"%d,&x);</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if(x%5＝＝0&&x%7＝＝0)</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;printf(“yes”);</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;printf(“no”);</p><p>}</p>', '2019-02-11 21:04:24');
INSERT INTO `question` VALUES ('320190211210558', '大题', 15, 'C语言', '<div class=\"exam-q\"><p>请编程序:根据以下函数关系,对输入的每个x值,计算出相应的y值。</p><p><img class=\"fr-fin\" data-fr-image-preview=\"false\" alt=\"Image title\" src=\"img/q_img/20190211212852upload图片2.png\" width=\"300\"></p><p><br></p></div>', '<p>&nbsp;&nbsp;&nbsp;&nbsp;main(){</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;int x;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;float y;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;scanf( \"%d\",&x );</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if (x&lt;0 )</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;y＝0;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else if(x&gt;0&&x&lt;＝10)</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;y＝x;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else if(x&gt;10&&x&lt;＝20)</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;y＝10;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else if(x&gt;20&&x&lt;40)</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;y＝－0.5*x＋20;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;y＝－1;</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if(y!＝－1)</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;printf(%f\",y);</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;printf(\"error\\n\");</p><p>&nbsp;&nbsp;&nbsp;&nbsp;}</p>', '2019-02-11 21:28:54');
INSERT INTO `question` VALUES ('320190211210904', '大题', 15, 'C语言', '<div class=\"exam-q\"><p>编程实现:输入一个整数,判断它能否被3,5,7整除，并输出以下信息之一:</p><p>(1)能同时被3,5,7整除;</p><p>(2)能被其中两数(要指出哪两个)整除;</p><p>(3)能被其中一个数(要指出哪一个)整除;</p><p>(4)不能被3,5,7任一个整除。</p></div>', '<p style=\"text-align: justify; margin-left: 20px;\">main(){</p><p style=\"text-align: justify; margin-left: 40px;\">int x;</p><p style=\"text-align: justify; margin-left: 40px;\">scanf(\"%d\",&x);</p><p style=\"text-align: justify; margin-left: 40px;\">if((x%3＝＝0&&(x%5＝＝0)&&(x%7＝＝0))</p><p style=\"text-align: justify; margin-left: 40px;\">&nbsp;&nbsp;&nbsp;&nbsp;printf(\"% d can be divided by3,5,7\\n\",x);</p><p style=\"text-align: justify; margin-left: 40px;\">else if((x%3＝＝0)8&(x%5＝＝0))</p><p style=\"text-align: justify; margin-left: 40px;\">&nbsp;&nbsp;&nbsp;&nbsp;printf(\"% d can be divided by3,5\\n\",x);</p><p style=\"text-align: justify; margin-left: 40px;\">else if((x%3＝＝0)&&(x%7＝＝0))</p><p style=\"text-align: justify; margin-left: 40px;\">&nbsp;&nbsp;&nbsp;&nbsp;printf(\"%d can be divided by3,7\\n\",x);</p><p style=\"text-align: justify; margin-left: 40px;\">else if((x%5＝＝0)&&(x%7＝＝0))</p><p style=\"text-align: justify; margin-left: 40px;\">&nbsp;&nbsp;&nbsp;&nbsp;printf(\"%d can be divided by5,7\\n\",x);</p><p style=\"text-align: justify; margin-left: 40px;\">else if(x%3＝＝0)</p><p style=\"text-align: justify; margin-left: 40px;\">&nbsp;&nbsp;&nbsp;&nbsp;printf(% d can be divided by3\\n\",x);</p><p style=\"text-align: justify; margin-left: 40px;\">else if(x%5＝＝0)</p><p style=\"text-align: justify; margin-left: 40px;\">&nbsp;&nbsp;&nbsp;&nbsp;printf(%d can be divided by5\\n\",x);</p><p style=\"text-align: justify; margin-left: 40px;\">else if(x%7＝＝0)</p><p style=\"text-align: justify; margin-left: 40px;\">&nbsp;&nbsp;&nbsp;&nbsp;printf(\"%d can be divided by7\\n\",x);</p><p style=\"text-align: justify; margin-left: 40px;\">else</p><p style=\"text-align: justify; margin-left: 40px;\">&nbsp;&nbsp;&nbsp;&nbsp;printf(\"% d can not be divided 3,5,7\\n\",x);</p><p style=\"text-align: justify; margin-left: 20px;\">}</p>', '2019-02-11 21:13:13');
INSERT INTO `question` VALUES ('320190211211357', '大题', 15, 'C语言', '<div class=\"exam-q\"><p>将以下程序段改用非嵌套的if语句实现。</p><p>ints,t,m;</p><p>t＝(int)(s/10);</p><p>switch(t)</p><p>{case10:m＝5;break;</p><p>case9:m＝4;break;</p><p>case8:m＝3;break;</p><p>case7:m＝2;break;</p><p>case6:m＝1;break；</p><p>defaultm＝0;</p><p>}</p></div>', '<p>ints,m;</p><p style=\"margin-left: 20px;\">if((s&lt;110)&&(s&gt;＝100))m＝5;</p><p style=\"margin-left: 20px;\">if((s&lt;100)&&.(s&gt;＝90))m＝4;</p><p style=\"margin-left: 20px;\">if((s&lt;90)&&(s&gt;＝80))m＝3;</p><p style=\"margin-left: 20px;\">if((s&lt;80)&8(s&gt;＝70))m＝2;</p><p style=\"margin-left: 20px;\">if((s&lt;70)8R(s&gt;＝60)&gt;m＝1;</p><p style=\"margin-left: 20px;\">if((s&lt;60)||(s&gt;109))m＝0;</p><p style=\"margin-left: 20px;\"><br></p>', '2019-02-11 21:14:15');
INSERT INTO `question` VALUES ('320190211211627', '大题', 15, 'C语言', '<div class=\"exam-q\"><p>用switch编程实现:</p><p><img class=\"fr-fin\" data-fr-image-preview=\"false\" alt=\"Image title\" src=\"img/q_img/20190211212820upload图片3.png\" width=\"195\"></p><p><br></p></div>', '<p style=\"margin-left: 20px;\">main(){</p><p style=\"margin-left: 20px;\">&nbsp;&nbsp;&nbsp;&nbsp;float x;</p><p style=\"margin-left: 20px;\">&nbsp;&nbsp;&nbsp;&nbsp;int y;</p><p style=\"margin-left: 20px;\">&nbsp;&nbsp;&nbsp;&nbsp;printf(\"\\ninputx:\");</p><p style=\"margin-left: 20px;\">&nbsp;&nbsp;&nbsp;&nbsp;scanf(\"%f\",&x);</p><p style=\"margin-left: 20px;\">&nbsp;&nbsp;&nbsp;&nbsp;switch(x&lt;0){</p><p style=\"margin-left: 20px;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case1:y＝－1;</p><p style=\"margin-left: 20px;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;</p><p style=\"margin-left: 20px;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case0:switch(x＝＝0){</p><p style=\"margin-left: 20px;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case1:y＝0;</p><p style=\"margin-left: 20px;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;</p><p style=\"margin-left: 20px;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;default:y＝1;</p><p style=\"margin-left: 20px;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}</p><p style=\"margin-left: 20px;\">&nbsp;&nbsp;&nbsp;&nbsp;}</p><p style=\"margin-left: 20px;\">&nbsp;&nbsp;&nbsp;&nbsp;printf(\"\\ny＝%d\",y);</p><p style=\"margin-left: 20px;\">}</p>', '2019-02-11 21:28:22');
INSERT INTO `question` VALUES ('320190211211755', '大题', 15, 'C语言', '<div class=\"exam-q\"><p>编程实现以下功能:读入两个运算数(data1和date2)及一个运算符(op),计算表达式data1	op	data2的值,其中op可为＋,－,*,/(用switch语句实现)。</p></div>', '<p style=\"margin-left: 20px;\">#include&lt;stdio.h&gt;</p><p style=\"margin-left: 20px;\">#include&lt;stdlib.h&gt;</p><p style=\"margin-left: 20px;\">void main(void){</p><p style=\"margin-left: 20px;\">&nbsp;&nbsp;&nbsp;&nbsp;float data1,data2,data3;</p><p style=\"margin-left: 20px;\">&nbsp;&nbsp;&nbsp;&nbsp;char op;</p><p style=\"margin-left: 20px;\">&nbsp;&nbsp;&nbsp;&nbsp;printf(\"\\nTypeinyourexpression:\");</p><p style=\"margin-left: 20px;\">&nbsp;&nbsp;&nbsp;&nbsp;scanf(\"%f%c%f\",&datal,&op,&data2);</p><p style=\"margin-left: 20px;\">&nbsp;&nbsp;&nbsp;&nbsp;switch(op){</p><p style=\"margin-left: 20px;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case\'＋\':data3＝data1＋data2;</p><p style=\"margin-left: 20px;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;</p><p style=\"margin-left: 20px;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case\'－\':data3＝data1－data2;</p><p style=\"margin-left: 20px;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;</p><p style=\"margin-left: 20px;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case\'*\':data3＝data1*data2;</p><p style=\"margin-left: 20px;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;</p><p style=\"margin-left: 20px;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case\'/\':if(data2＝＝0){</p><p style=\"margin-left: 20px;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;printf(\"\\nDivisionbyzero!\");</p><p style=\"margin-left: 20px;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;exit(1);}</p><p style=\"margin-left: 20px;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;data3＝＝data1/data2;</p><p style=\"margin-left: 20px;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;</p><p style=\"margin-left: 20px;\">}</p><p style=\"margin-left: 20px;\">printf(\"Thisis%6.2f%c%6.2f＝%6.2f\\n\",data1,op,data2,data3);</p><p style=\"margin-left: 20px;\">}</p>', '2019-02-11 21:17:55');
INSERT INTO `question` VALUES ('320190211214752', '大题', 15, '数据库', '<div class=\"exam-q\"><p>123——大题专用测试——数据库</p><p><img class=\"fr-fin\" data-fr-image-preview=\"false\" alt=\"Image title\" src=\"img/q_img/20190211215109upload哈哈.png\" width=\"300\"></p><p><br></p></div>', '<p><span =\"\"=\"\" pingfang=\"\" style=\"color: rgb(51, 51, 51);\">在 Bootstrap 2 中，我们对框架中的某些关键部分增加了对移动设备友好的样式。而在 Bootstrap 3 中，我们重写了整个框架，使其一开始就是对移动设备友好的。这次不是简单的增加一些可选的针对移动设备的样式，而是直接融合进了框架的内核中。也就是说，</span>Bootstrap 是移动设备优先的<span =\"\"=\"\" pingfang=\"\" style=\"color: rgb(51, 51, 51);\">。针对移动设备的样式融合进了框架的每个角落，而不是增加一个额外的文件。</span></p><p style=\"box-sizing: border-box; margin: 0px; line-height: 1.75; color: rgb(51, 51, 51); font-family: -apple-system, system-ui, BlinkMacSystemFont, \" ui\",=\"\" roboto,=\"\" \"helvetica=\"\" neue\",=\"\" arial,=\"\" \"pingfang=\"\" sc\",=\"\" \"hiragino=\"\" gb\",=\"\" \"microsoft=\"\" yahei\",=\"\" sans-serif;=\"\" font-size:=\"\" 14px;=\"\" font-style:=\"\" normal;=\"\" font-variant-ligatures:=\"\" font-variant-caps:=\"\" font-weight:=\"\" 400;=\"\" letter-spacing:=\"\" orphans:=\"\" 2;=\"\" text-align:=\"\" start;=\"\" text-indent:=\"\" 0px;=\"\" text-transform:=\"\" none;=\"\" white-space:=\"\" widows:=\"\" word-spacing:=\"\" -webkit-text-stroke-width:=\"\" background-color:=\"\" rgb(255,=\"\" 255,=\"\" 255);=\"\" text-decoration-style:=\"\" initial;=\"\" text-decoration-color:=\"\" initial;\"=\"\"><br></p>', '2019-02-11 21:51:12');

-- ----------------------------
-- Table structure for teacher
-- ----------------------------
DROP TABLE IF EXISTS `teacher`;
CREATE TABLE `teacher`  (
  `id` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '教师登录id',
  `password` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '教师登录密码',
  `name` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '教师姓名',
  `contact` varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '教师联系方式',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Records of teacher
-- ----------------------------
INSERT INTO `teacher` VALUES ('201511010120', '123456', '李老师', '111111');
INSERT INTO `teacher` VALUES ('201511010121', '123456', '丁老师', '222222');
INSERT INTO `teacher` VALUES ('201511010122', '123456', '王老师', '444444');
INSERT INTO `teacher` VALUES ('201511010123', '199612', '张老师', '1053338363');
INSERT INTO `teacher` VALUES ('201511010124', '000000', '李哈哈', '888888');

SET FOREIGN_KEY_CHECKS = 1;
